-- return {
-- 	"linux-cultist/venv-selector.nvim",
-- 	dependencies = { "neovim/nvim-lspconfig", "nvim-telescope/telescope.nvim" },
-- 	config = function()
-- 		require("venv-selector").setup({
-- 			pipenv_path = vim.fn.expand("~/.virtualenvs/"),
-- 			path = vim.fn.expand("~/.venvs"),
-- 			name = { ".venv", "scientific-venv", "venv" },
-- 			parents = 0,
-- 		})
-- 	end,
-- 	event = "VeryLazy", -- Optional: needed only if you want to type `:VenvSelect` without a keymapping
-- }
